# Energy News Bot - LLM Prompts

# Filter prompt: Determines if article is relevant to the energy industry
filter_prompt: |
  Is this article about the energy industry (production, infrastructure, markets, policy)?
  
  INCLUDE if about:
  - Energy production (oil, gas, coal, nuclear, solar, wind, hydro, etc.)
  - Power generation projects and companies
  - Energy discoveries (oil/gas reserves, mineral deposits)
  - Transmission & distribution grid infrastructure
  - Utility companies and operations
  - Energy markets, pricing, trading, contracts (PPAs, etc.)
  - Energy storage and battery systems (utility-scale)
  - Data centers and their power consumption/infrastructure
  - AI infrastructure energy demand
  - Energy policy, regulations, FERC/state commission decisions
  - Wholesale power markets (PJM, CAISO, ERCOT, etc.)
  - Energy company announcements (new reactors, projects, M&A)
  - Energy technology (SMRs, turbines, grid tech, etc.)
  
  EXCLUDE (consumer products, not industry):
  - Electric vehicles (EVs), car sales, charging stations
  - Consumer appliances (heat pumps, water heaters, home HVAC)
  - Residential solar panels or home batteries
  - Climate activism or environmental protests
  - General climate science (unless tied to energy policy)
  
  Article Title: {title}
  Article Summary: {summary}
  
  Answer with ONLY: Yes or No
  If Yes, provide brief reason (1 sentence)

# Tweet generation prompt: Creates engaging, concise tweets
tweet_prompt: |
  Create a concise tweet about this energy news article.
  
  Article Title: {title}
  Article Summary: {summary}
  Article URL: {url}
  
  STRICT RULES:
  - Start with: 🚨 BREAKING: [relevant emoji] then the news
  - Choose ONE relevant emoji based on topic: ⚡(energy/power) ☀️(solar) 💨(wind) 🔋(battery/storage) 💰(funding) 🏗️(construction) ⚛️(nuclear) 🌊(hydro)
  - MAXIMUM 230 characters total (including the 🚨 BREAKING: prefix and emoji)
  - **ALWAYS include specific numbers, metrics, and quantities from the article** (MW, GW, $millions, project sizes, percentages, etc.)
  - Include company names, project names, and locations when available
  - NO hashtags ever (#)
  - NO URLs or links in the tweet text (we add those separately)
  - NO line breaks - write as a single paragraph
  - Keep it factual and professional
  - Make each tweet unique
  
  Example format: 🚨 BREAKING: ⚡ Madison Energy acquires NextEra's 900 MW distributed solar portfolio across 25 states, expanding to nearly 1 GW of operating assets.
  
  Generate ONLY the tweet text as a single paragraph, nothing else. Do NOT include any URLs.

# Hashtag generation prompt
hashtag_prompt: |
  Based on this article, suggest 2-3 relevant hashtags.
  
  Article: {title}
  
  Choose from these categories:
  - Technology: #Solar #Wind #Nuclear #Hydrogen #Storage #EV
  - Market: #Energy #CleanEnergy #RenewableEnergy #PowerMarket
  - Policy: #EnergyPolicy #CleanPower #GreenEnergy
  - Location: #California #Texas #Offshore #US
  - Data/AI: #DataCenters #AI #TechInfrastructure #AIEnergy
  
  Return ONLY the hashtags, space-separated, no explanations.
  Example: #Solar #California #CleanEnergy

# Image extraction prompt
image_prompt: |
  Look at this article and identify the best image URL.
  
  Article HTML: {html}
  
  Priority order:
  1. Featured/hero image
  2. First content image
  3. Open Graph image (og:image)
  4. Twitter card image
  
  Return ONLY the image URL, nothing else.
  If no image found, return: NONE
